baseurl = "https://testes.wsouza.com.br"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "dicaslinuxewindows" # Enable comments by entering your Disqus shortname
googleAnalytics = "G-ZE9HZB2464" # Enable Google Analytics by entering your tracking id
enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true
external = true

[[menu.main]]             
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Categorias"
  weight = 20
  identifier = "categories"
  url = "/post/"
[[menu.main]]
  name = "Sistemas"
  weight = 30
  identifier = "system"
  url = "/sistemas.html"
[[menu.main]]
  name = "Sobre"
  weight = 40
  identifier = "about"
  url = "/sobre.html"
  
  
  [menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "category"
    name = "Category"
    url = "/category"
    weight = 2
  [[menu.main]]
    identifier = "category1"
    name = "Category1"
    url = "/tags/category1"
    parent = "category"
    weight = 1
  [[menu.main]]
    identifier = "category2"
    name = "Category2"
    url = "/tags/category2"
    parent = "category"
    weight = 2
  [[menu.main]]
    identifier = "category3"
    name = "Category3"
    url = "/tags/category3"
    parent = "category"
    weight = 3
  [[menu.main]]
    identifier = "another-category"
    name = "Another Category"
    url = "/another-category"
    weight = 3
  [[menu.main]]
    identifier = "another-category1"
    name = "Another Category1"
    url = "/tags/another-category1"
    parent = "another-category"
    weight = 1
  [[menu.main]]
    identifier = "another-category2"
    name = "Another Category2"
    url = "/tags/another-category2"
    parent = "another-category"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About Us"
    url = "/about/"
    weight = 4
  
  
  

[Author]
  name = "W.Souza"
  bio = "Usuário de Debian e Windows. Gosto de compartilhar as experiências e dificuldades encontradas no dia-a-dia."
  avatar = "https://3.bp.blogspot.com/-n7mOFEUoIG0/XFxGIo7WVzI/AAAAAAAAKac/rQpmdra-miYaFf_6uSovTWmQD7SseNtngCK4BGAYYCw/s107/Dicas%2BLinux%2Be%2BWindows_TemplateNovo%2Bc%25C3%25B3pia.png"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params]
  description = "" # Description of your site
  opengraph = true
  copyright = "WSouza"
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  toc = false # Enable Table of Contents
  readmore = true # Show "Read more" button in list if true
  authorbox = true
  pager = true
  keyword = "Windows, Linux, Mobile, Internet, Android"
  post_meta = ["author", "date", "categories", "translations"]
  googleAnalyticsID = "G-ZE9HZB2464"
  show_translations= true
  dateFormat = "Mon, Jan 2, 2006"

[Params.thumbnail]
  visibility = ["list", "post"] # Control thumbnail visibility
  
[Params.logo]
  image = ""
  title = "WSouza"
  subtitle = "Dicas Linux e Windows" # Logo subtitle

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "false" # Configure layout for single pages
  widgets = ["languages", "search", "recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)
  
  [Params.widgets.social]
  # Enable parts of social widget
  twitter = "dicaslnxwindows"
  github = "andradeswagner"
  email = "dicaslinuxewindows@gmail.com"
  
  [[Params.widgets.social.custom]]
  title = "Youtube"
  url = "https://youtube.com/channel/UCdgAIchdOo7lsyKge8m-P_w"
  icon = "svg/youtube3.svg" # Optional. Path relative to "layouts/partials"
